server:
  shutdown: graceful
  port: 8081
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: apigw-ckcspoc
  main:
    allow-circular-references: true # TODO: ClientsCommunicationService <-> OnlineCnpPaymentService
  web:
    resources:
      add-mappings: false
  lifecycle:
    timeout-per-shutdown-phase: 1m #graceful timout to complete currentlly running requests
  servlet.multipart:
    max-file-size: 349MB
    max-request-size: 350MB
  datasource:
    url: jdbc:postgresql://localhost:32432/rhapsody
    username: rhapsody
    password: p123456
  jpa:
    properties:
      hibernate:
        # Log requests from
        # Hibernate to PostgreSQL
        # Temporary for our development
        show_sql: true
        use_sql_comments: true
        format_sql: true

async:
  provider-timeout-seconds: 60

swagger.base-path: apigw-ckcspoc

asset:
  prefix:
    apigw: /apigw-ckcspoc
    cdn: /cdn
    private: /private
    public: /public

ckcs:
  auth:
    environmentId: ${CKCS_ENVIRONMENT_ID}
    apiSecret: ${CKCS_API_SECRET}
    accessKey: ${CKCS_ACCESS_KEY}

ckcs-organization-id: "89797"
ckcs-client-api-url: "https://${ckcs-organization-id}.cke-cs.com/api/v5/${ckcs.auth.environmentId}"
ckcs-uses-doc-storage: ${CKCS_USES_DOC_STORAGE:true}
ckcs-sync-doc-storage: ${CKCS_SYNC_DOC_STORAGE:true}
